package ro.bighealth.commons.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.2
 * Fri Oct 31 16:37:06 EET 2014
 * Generated source version: 2.1.2
 * 
 */
 
@WebService(targetNamespace = "http://service.commons.bighealth.ro", name = "userAxisServicePortType")
@XmlSeeAlso({ro.bighealth.commons.entity.xsd.ObjectFactory.class,ro.bighealth.commons.core.xsd.ObjectFactory.class,ObjectFactory.class})
public interface UserAxisServicePortType {

    @WebMethod(action = "urn:findByEmail")
    @Action(input = "urn:findByEmail", output = "urn:findByEmailResponse")
    @RequestWrapper(localName = "findByEmail", targetNamespace = "http://service.commons.bighealth.ro", className = "ro.bighealth.commons.service.FindByEmail")
    @ResponseWrapper(localName = "findByEmailResponse", targetNamespace = "http://service.commons.bighealth.ro", className = "ro.bighealth.commons.service.FindByEmailResponse")
    @WebResult(name = "return", targetNamespace = "http://service.commons.bighealth.ro")
    public java.util.List<ro.bighealth.commons.entity.xsd.User> findByEmail(
        @WebParam(name = "email", targetNamespace = "http://service.commons.bighealth.ro")
        java.lang.String email
    );
}
